import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navs/Header";
import Footer from "@/components/Navs/Footer";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const groove = localFont({
  src:[
    {
      path:"../public/Font/Blanc Groove Font/OTF/BlancGroove-ExtraBold.otf"
    }
  ],
  variable: '--font-groove'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`back ${groove.variable}`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
